In [9]:
%config Completer.use_jedi = False

In [4]:
import pyodbc
import pandas as pd
from time import gmtime, strftime
from alpha_vantage.timeseries import TimeSeries
import time
import QuantLib as ql
from utilities.date_utilities import *

In [5]:
ts = TimeSeries(key='NHXLC1G323WY6E6I', output_format='pandas')

In [6]:
ts.get_daily_adjusted?

In [11]:
import alpha_vantage as alpha

In [8]:
data = ts.get_daily_adjusted("AAPL", outputsize='compact')[0]
data

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient
date,,,,,,,,
2021-06-11,126.53,127.44,126.1000,127.35,127.350000,53522373.0,0.0,1.0
2021-06-10,127.02,128.19,125.9400,126.11,126.110000,71186421.0,0.0,1.0
2021-06-09,127.21,127.75,126.5200,127.13,127.130000,56877937.0,0.0,1.0
2021-06-08,126.60,128.46,126.2101,126.74,126.740000,74403774.0,0.0,1.0
2021-06-07,126.17,126.32,124.8321,125.90,125.900000,71057550.0,0.0,1.0
...,...,...,...,...,...,...,...,...
2021-01-26,143.60,144.30,141.3700,143.16,142.704617,98390555.0,0.0,1.0
2021-01-25,143.07,145.09,136.5400,142.92,142.465381,157611713.0,0.0,1.0
2021-01-22,136.28,139.85,135.0200,139.07,138.627627,114459360.0,0.0,1.0
2021-01-21,133.80,139.67,133.5900,136.87,136.434625,120529544.0,0.0,1.0
2021-01-20,128.66,132.49,128.5500,132.03,131.610021,104319489.0,0.0,1.0